#!/usr/bin/env python
#
# vim:sw=4:ts=4:expandtab
#
# Note: We could have use the list() method of tarfile to get the file content
#  but it does not set the first bit of the ls output...

import datetime
import opkg
import os
import sys
import stat
import md5
from opkg_hash import opkg_print_hash

def usage():
    sys.stderr.write("%s file.ipk\n" % sys.argv[0])
    sys.exit(1)

if len(sys.argv) < 2:
    usage()

rc = 0

packages = sys.argv[1:]
if len(packages) > 1:
    for package in packages:
        try:
            opkg_print_hash(package, md5, True)
        except:
            sys.stderr.write("%s: Error while opening %s\n" % (sys.argv[0],
                                                               package))
            rc = 1
        print("")
else:
    rc = opkg_print_hash(sys.argv[1], md5)

sys.exit(rc)
